In [21]:
from api_query import get_wikitext
import re

Title = "Liste der Vögel Deutschlands"
data = get_wikitext(Title)

In [22]:
print(data)

Die '''Liste der Vögel Deutschlands''' führt die Arten der [[Vögel]] (Aves) auf, deren Vorkommen in [[Deutschland]] beobachtet worden sind.

Sie enthält nur Arten, deren Feststellung von den zuständigen ornithologischen Gremien (zum Beispiel durch die Deutsche Avifaunistische Kommission (DAK)<ref>[https://www.dda-web.de/dak Dachverband Deutscher Avifaunisten – Über die DAK], abgerufen am 17. Dezember 2022</ref> oder entsprechende Einrichtungen auf Länderebene) anerkannt und in einschlägigen Fachzeitschriften publiziert wurden. Außerdem werden an dieser Stelle nur die Arten berücksichtigt, deren Beobachtung auf Feststellung wildlebender Tiere zurückzuführen ist sowie diejenigen, die eingebürgert sind, das heißt, die ursprünglich in anderen Regionen vorkommen, die sich jedoch inzwischen durch Fortpflanzung längerfristig etabliert haben.

Grundlage für die nachfolgende Liste ist die ''Liste der Vögel Deutschlands – Version 3.2'' mit dem Stand vom 30. Juni 2019, wie sie von Peter H. Barthel und Thorsten Krüger auf der Website der [[Deutsche Ornithologen-Gesellschaft|Deutschen Ornithologen-Gesellschaft]] (DO-G) publiziert wurde.<ref>''[https://www.do-g.de/fileadmin/Ablage/DOG/Fachkommissionen/Kommission_Artenliste/Dokumente/Barthel_Kr%C3%BCger_2019_Liste_der_V%C3%B6gel_Deutschlands_3.2.pdf Liste der Vögel Deutschlands 3.2]'' (PDF, 471&nbsp;KB)</ref> Die taxonomische Reihenfolge und Nomenklatur entspricht der in der genannten Quelle. Ergänzungen in späteren Veröffentlichungen auf Veranlassung der ornithologischen Gremien werden nacherfasst.

Die unter Status eingetragenen Bezeichnungen weisen auf die Art des Vorkommens hin. Die Angabe „[[Brutvogel]]“ kennzeichnet Arten, die sich in Deutschland fortpflanzen. Mit der Angabe „eingebürgert“ handelt es sich dabei um eine vom Menschen eingeführte Art ([[Neozoon]]); mit der Angabe „selten“ brüten deutschlandweit weniger als 100 Paare; mit der Angabe „lokal“ beschränkt sich das Brutvorkommen auf sehr kleine Regionen, z.&nbsp;B. [[Helgoland]] oder einzelne Städte. Als „[[Standvogel|Jahresvogel]]“ sind Arten bezeichnet, die im ganzen Jahresverlauf festzustellen sind. „[[Zugvögel]]“ verlassen Deutschland im Winter oder diese Arten ziehen als Bewohner anderer Regionen durch Deutschland hindurch. Als „Wintergast“ sind Brutvögel anderer Regionen bezeichnet, die Deutschland zum Überwintern aufsuchen. Wenn die jeweilige Angabe mit der Ergänzung „selten“ versehen ist, beläuft sich die Anzahl der Individuen jeweils auf weniger als 100. Die Angabe „Ausnahmeerscheinung“ kennzeichnet Arten, die nur selten in Deutschland festgestellt werden. Dies trifft zu, wenn im Durchschnitt weniger als fünf Nachweise pro Jahr oder seit 1950 insgesamt weniger als fünf Nachweise (dann als „besondere Ausnahmeerscheinung“ bezeichnet) erbracht wurden.<ref>Statusangaben vereinfacht nach: ''[https://www.do-g.de/fileadmin/Ablage/DOG/Fachkommissionen/Kommission_Artenliste/Dokumente/Barthel_Kr%C3%BCger_2019_Liste_der_V%C3%B6gel_Deutschlands_3.2.pdf Liste der Vögel Deutschlands 3.2]'' (PDF, 471&nbsp;KB)</ref>

Die unter RL-Status verzeichneten Ziffern und Buchstaben verweisen auf den Status in der ''[[Rote Liste der Brutvögel Deutschlands|Roten Liste der Brutvögel]]'' in der 6. Fassung, veröffentlicht im Juni 2021,<ref>[https://www.nabu.de/tiere-und-pflanzen/voegel/artenschutz/rote-listen/roteliste-2021.html ''Rote Liste der Brutvögel Deutschlands 2021'' laut Website des NABU]</ref> und haben folgende Bedeutung: 0 – diese Art ist als Brutvogel in Deutschland ausgestorben; 1 – diese Art ist in Deutschland vom Aussterben bedroht; 2 – diese Art ist in Deutschland stark gefährdet; 3 – diese Art ist in Deutschland gefährdet; R – diese Art ist wegen geografischer Restriktionen in Deutschland extrem selten; V – diese Art befindet sich auf der Vorwarnliste.

== [[Galliformes]] – Hühnervögel ==
=== [[Phasianidae]] – Fasanverwandte ===
{| class="wikitable"
! width="12%"| Bild
! width="18%"| deutscher Name
! width="18%"| wissenschaftlicher Name
! width="22%"| Status
! width="8%"| RL-Status
! width="22%"| Bemerkung
|- style="vertical-align:top"
|[[Datei:Haselhuhn-01.jpg|120px|Haselhuhn]]||[[Haselhuhn]]||''Tetrastes bonasia''||Brut-, Jahresvogel||2||
|- style="vertical-align:top"
|[[Datei:Tetrao urogallus, Glenfeshie, Scotland 1.jpg|120px|Auerhuhn]]||[[Auerhuhn]]||''Tetrao urogallus''||Brut-, Jahresvogel||1||
|- style="vertical-align:top"
|[[Datei:Flickr - Rainbirder - Black Grouse (Tetrao tetrix) Male.jpg|120px|Birkhuhn]]||[[Birkhuhn]]||''Lyrurus tetrix''||Brut-, Jahresvogel||2||
|- style="vertical-align:top"
|[[Datei:Lagopus muta2.jpg|120px|Alpenschneehuhn]]||[[Alpenschneehuhn]]||''Lagopus muta''||Brut-, Jahresvogel||R||
|- style="vertical-align:top"
|[[Datei:Steinhuhn.jpg|120px|Steinhuhn]]||[[Steinhuhn]]||''Alectoris graeca''||seltener, lokaler Brut-, Jahresvogel||R||
|- style="vertical-align:top"
|[[Datei:Rebhuehner.jpg|120px|Rebhuhn]]||[[Rebhuhn]]||''Perdix perdix''||Brut-, Jahresvogel||2||
|- style="vertical-align:top"
|[[Datei:Coturnix coturnix, Fraunberg, Bayern, Deutschland 1.jpg|120px|Wachtel]]||[[Wachtel (Art)|Wachtel]]||''Coturnix coturnix''||Brut-, Zugvogel||V||
|- style="vertical-align:top"
|[[Datei:Male and female pheasant.jpg|120px|Fasan]]||[[Jagdfasan]]||''Phasianus colchicus''||eingeführter Brut-, Jahresvogel|| ||
|}

== [[Anseriformes]] – Entenvögel ==
=== [[Anatidae]] – Entenverwandte ===
{| class="wikitable"
! width="12%"| Bild
! width="18%"| deutscher Name
! width="18%"| wissenschaftlicher Name
! width="22%"| Status
! width="8%"| RL-Status
! width="22%"| Bemerkung
|- style="vertical-align:top"
|[[Datei:Branta bernicla bernicla - Brent-Goose.jpg|120px|Ringelgans]]||[[Ringelgans]]||''Branta bernicla''||Zugvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Red breasted goose.jpg|120px|Rothalsgans]]||[[Rothalsgans]]||''Branta ruficollis''||seltener Zugvogel, Wintergast|| ||Bruten gehen auf entflogene Tiere zurück
|- style="vertical-align:top"
|[[Datei:Canada-Goose-Szmurlo.jpg|120px|Kanadagans]]||[[Kanadagans]]||''Branta canadensis''||eingeführter Brut-, Jahresvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Weißwangengans oder Nonnengans, Branta leucopsis 3.JPG|120px|Weißwangengans]]||[[Weißwangengans]]||''Branta leucopsis''||Brut-, Jahresvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Anser indicus- Streifengans Englischer Garten Muenchen-2.jpg|120px|Streifengans]]||[[Streifengans]]||''Anser indicus''||eingeführter, seltener Jahres-, Zugvogel|| ||Gastvogel aus etablierten, eingeführten Brutpopulationen benachbarter Länder; Bruten gehen auf ausgesetzte Tiere zurück
|- style="vertical-align:top"
|[[Datei:Greylag-Goose.jpg|120px|Graugans]]||[[Graugans]]||''Anser anser''||Brut-, Jahres-, Zugvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Anser fabalis fabalis, RSPB Saltholme 2.jpg|120px|Waldsaatgans]]||[[Waldsaatgans]]||''Anser fabalis''||Zugvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:KurzschnabelgansRL.jpg|120px|Kurzschnabelgans]]||[[Kurzschnabelgans]]||''Anser brachyrhynchus''||Zugvogel, Wintergast|| ||Bruten gehen auf entflogene Tiere zurück
|- style="vertical-align:top"
|[[Datei:Tundra Bean Goose.jpg|120px|Tundrasaatgans]]||[[Tundrasaatgans]]||''Anser serrirostris''||Zugvogel, Wintergast|| ||Bruten gehen auf entflogene Tiere zurück
|- style="vertical-align:top"
|[[Datei:Greater white-fronted goose (cropped).jpg|120px|Blässgans]]||[[Blässgans]]||''Anser albifrons''||Zugvogel, Wintergast|| ||Bruten gehen auf entflogene Tiere zurück
|- style="vertical-align:top"
|[[Datei:Ente unbekannt 1.jpg|120px|Zwerggans]]||[[Zwerggans]]||''Anser erythropus''||seltener Zugvogel und Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Mute swan Vrhnika.jpg|120px|Höckerschwan]]||[[Höckerschwan]]||''Cygnus olor''||Brut-, Jahres-, Zugvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Cygnus bewickii 01.jpg|120px|Zwergschwan]]||[[Zwergschwan]]||''Cygnus bewickii''||Zugvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Cygnus cygnus Singschwan.jpg|120px|Singschwan]]||[[Singschwan]]||''Cygnus cygnus''||seltener Brutvogel; Zugvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Alopochen-aegyptiacus.jpg|120px|Nilgans]]||[[Nilgans]]||''Alopochen aegyptiaca''||eingeführter Brut-, Jahresvogel|| ||
|- style="vertical-align:top"
|[[Datei:Common.shelduck.2.arp.750pix.jpg|120px|Brandgans]]||[[Brandgans]]||''Tadorna tadorna''||Brut-, Jahres-, Zugvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:rostgans.jpg|120px|Rostgans]]||[[Rostgans]]||''Tadorna ferruginea''||eingeführter Brut-, Jahresvogel, seltener Wintergast|| ||vor 1950 als Wildvogel nachgewiesen
|- style="vertical-align:top"
|[[Datei:Mandarin ducks.jpg|120px|Mandarinente]]||[[Mandarinente]]||''Aix galericulata''||eingeführter Brut-, Jahresvogel|| ||
|- style="vertical-align:top"
|[[Datei:Garganey (Spatula querquedula) male.jpg|120px|Knäkente]]||[[Knäkente]]||''Spatula querquedula''||Brut-, Zugvogel||1||
|- style="vertical-align:top"
|[[Datei:Bluewingedteal54.jpg|120px|Blauflügelente]]||[[Blauflügelente]]||''Spatula discors''||Ausnahmeerscheinung|| ||
|- style="vertical-align:top"
|[[Datei:Spatula clypeata Oulu Finland 2016-05-07.jpg|120px|Löffelente]]||[[Löffelente]]||''Spatula clypeata''||Brut-, Jahres-, Zugvogel, Wintergast||3||
|- style="vertical-align:top"
|[[Datei:Anas-strepera-001.jpg|120px|Schnatterente]]||[[Schnatterente]]||''Mareca strepera''||Brut-, Jahres-, Zugvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Anas penelope 001.jpg|120px|Pfeifente]]||[[Pfeifente]]||''Mareca penelope''||seltener Brutvogel; Jahres-, Zugvogel, Wintergast||R||
|- style="vertical-align:top"
|[[Datei:American Wigeon pair.JPG|120px|Nordamerikanische Pfeifente]]||[[Kanadapfeifente]]||''Mareca americana''||Ausnahmeerscheinung|| ||
|- style="vertical-align:top"
|[[Datei:Stockente Anas platyrhynchos Couple Richard Bartz.jpg|120px|Stockente]]||[[Stockente]]||''Anas platyrhynchos''||Brut-, Jahres-, Zugvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Male northern pintail at Llano Seco.jpg|120px|Spießente]]||[[Spießente]]||''Anas acuta''||seltener Brutvogel; Jahres-, Zugvogel, Wintergast||2||
|- style="vertical-align:top"
|[[Datei:Anas crecca (male).JPG|120px|Krickente]]||[[Krickente]]||''Anas crecca''||Brut-, Jahres-, Zugvogel, Wintergast||3||
|- style="vertical-align:top"
|[[Datei:Anas carolinensis FWS.jpg|120px|Carolinakrickente]]||[[Carolinakrickente]]||''Anas carolinensis''||Ausnahmeerscheinung|| ||
|- style="vertical-align:top"
|[[Datei:Marbled.teal.arp.600pix.jpg|120px|Marmelente]]||[[Marmelente]]||''Marmaronetta angustirostris''||besondere Ausnahmeerscheinung|| ||als Wildvogel nur vor 1950 nachgewiesen; Nachweise seit 1950 betreffen wohl keine Wildvögel
|- style="vertical-align:top"
|[[Datei:Red-crested-pochard.JPG|120px|Kolbenente]]||[[Kolbenente]]||''Netta rufina''||Brut-, Jahres-, Zugvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Duck WUXGA.jpg|120px|Tafelente]]||[[Tafelente]]||''Aythya ferina''||Brut-, Jahres-, Zugvogel, Wintergast||V||
|- style="vertical-align:top"
|[[Datei:Aythya nyroca at Martin Mere 1.jpg|120px|Moorente]]||[[Moorente]]||''Aythya nyroca''||seltener, lokaler Brut-, Zugvogel, Wintergast||1||
|- style="vertical-align:top"
|[[Datei:Aythya collaris1.jpg|120px|Ringschnabelente]]||[[Ringschnabelente]]||''Aythya collaris''||Ausnahmeerscheinung|| ||
|- style="vertical-align:top"
|[[Datei:Aythya-fuligula Tufted-Duck.jpg|120px|Reiherente]]||[[Reiherente]]||''Aythya fuligula''||Brut-, Jahres-, Zugvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Greater-scaup-male2.jpg|120px|Bergente]]||[[Bergente]]||''Aythya marila''||lokaler Brutvogel; Jahres-, Zugvogel, Wintergast||R||
|- style="vertical-align:top"
|[[Datei:Lesser Scaup (male) - Aythya affinis, Oakley Street, Cambridge, Maryland.jpg|120px|Kanadabergente]]||[[Kanadabergente]]||''Aythya affinis''||besondere Ausnahmeerscheinung|| ||Bruten gehen auf entflogene Tiere zurück
|- style="vertical-align:top"
|[[Datei:Stellersdrake2.jpg|120px|Scheckente]]||[[Scheckente]]||''Polysticta stelleri''||Ausnahmeerscheinung|| ||
|- style="vertical-align:top"
|[[Datei:Prachteiderente 0505281 Ausschnitt.jpg|120px|Prachteiderente]]||[[Prachteiderente]]||''Somateria spectabilis''||Ausnahmeerscheinung|| ||
|- style="vertical-align:top"
|[[Datei:Somateria mollissima male female.jpg|120px|Eiderente]]||[[Eiderente]]||''Somateria mollissima''||Brut-, Jahres-, Zugvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Histrionicus histrionicus 001.jpg|120px|Kragenente]]||[[Kragenente]]||''Histrionicus histrionicus''||besondere Ausnahmeerscheinung|| ||als Wildvogel nur vor 1950 nachgewiesen; Herkunft seit 1950 nachgewiesener Tiere ungewiss
|- style="vertical-align:top"
|[[Datei:Melanitta perspicillata.jpg|120px|Brillenente]]||[[Brillenente]]||''Melanitta perspicillata''||besondere Ausnahmeerscheinung|| ||
|- style="vertical-align:top"
|[[Datei:Wwscoter12.JPG|120px|Samtente]]||[[Samtente]]||''Melanitta fusca''||Zugvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Melanitta stejnegeri.jpg|120px|Kamtschatkasamtente]]||[[Kamtschatkasamtente]]||''Melanitta stejnegeri''||besondere Ausnahmeerscheinung|| ||
|- style="vertical-align:top"
|[[Datei:Melanitta nigra (cropped).jpg|120px|Trauerente]]||[[Trauerente]]||''Melanitta nigra''||Zugvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Melanitta americana Barnegat NJ.jpg|120px|Pazifiktrauerente]] ||[[Pazifiktrauerente]]||''Melanitta americana''||besondere Ausnahmeerscheinung|| ||
|- style="vertical-align:top"
|[[Datei:Long-tailed-duck.jpg|120px|Eisente]]||[[Eisente]]||''Clangula hyemalis''||Zugvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Common Goldeneye.jpg|120px|Schellente]]||[[Schellente]]||''Bucephala clangula''||Brut-, Zugvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Barrowgoldeneye.jpg|120px|Spatelente]]||[[Spatelente]]||''Bucephala islandica''||besondere Ausnahmeerscheinung|| ||als Wildvogel nur vor 1950 nachgewiesen; Nachweise seit 1950 betreffen wohl keine Wildvögel
|- style="vertical-align:top"
|[[Datei:Smew.both.arp.600pix.jpg|120px|Zwergsäger]]||[[Zwergsäger]]||''Mergus albellus''||Zugvogel, Wintergast|| ||Bruten gehen auf entflogene Tiere zurück
|- style="vertical-align:top"
|[[Datei:Gaensesaeger.jpg|120px|Gänsesäger]]||[[Gänsesäger]]||''Mergus merganser''||Brut-, Zugvogel, Wintergast||3||
|- style="vertical-align:top"
|[[Datei:Mergus serrator.jpg|120px|Mittelsäger]]||[[Mittelsäger]]||''Mergus serrator''||Brut-, Zugvogel, Wintergast|| ||
|- style="vertical-align:top"
|[[Datei:Oxyura jamaicensis FWS.jpg|120px|Schwarzkopf-Ruderente]]||[[Schwarzkopf-Ruderente]]||''Oxyura jamaicensis''||seltener Jahresvogel|| ||Gastvogel aus etablierten, eingeführten Brutpopulationen benachbarter Länder
|- style="vertical-align:top"
|[[Datei:Weißkopfruderente Oxyura leucocephala 050324 Ausschnitt.jpg|120px|Weißkopf-Ruderente]]||[[Weißkopf-Ruderente]]||''Oxyura leucocephala''||Ausnahmeerscheinung|| ||als Wildvogel nur vor 1950 nachgewiesen; Herkunft seit 1950 nachgewiesener Tiere ungewiss
|}

== [[Caprimulgiformes]] – Nachtschwalbenvögel ==
=== [[Caprimulgidae]] – Nachtschwalben ===
{| class="wikitable"
! width="12%"| Bild
! width="18%"| deutscher Name
! width="18%"| wissenschaftlicher Name
! width="22%"| Status
! width="8%"| RL-Status
! width="22%"| Bemerkung
|- style="vertical-align:top"
|[[Datei:Şivanxapînok (cropped).jpg|120px|Ziegenmelker]]||[[Ziegenmelker]]||''Caprimulgus europaeus''||Brut-, Zugvogel||3||
|- style="vertical-align:top"
|[[Datei:Caprimulgus aegyptius.jpg|120px|Pharaonen-Ziegenmelker]]||[[Pharaonen-Ziegenmelker]]||''Caprimulgus aegyptius''|| || ||als Wildvogel nur vor 1950 nachgewiesen
|}

== [[Apodiformes]] – Seglervögel ==
=== [[Apodidae]] – Segler ===
{| class="wikitable"
! width="12%"| Bild
! width="18%"| deutscher Name
! width="18%"| wissenschaftlicher Name
! width="22%"| Status
! width="8%"| RL-Status
! width="22%"| Bemerkung
|- style="vertical-align:top"
|[[Datei:Alpi1.jpg|120px|Alpensegler]]||[[Alpensegler]]||''Tachymarptis melba''||lokaler Brut-, Zugvogel|| ||
|- style="vertical-align:top"
|[[Datei:ApusApusKlausRoggel05.jpg|120px|Mauersegler]]||[[Mauersegler]]||''Apus apus''||Brut-, Zugvogel|| ||
|- style="vertical-align:top"
|[[Datei:Apuspallidus 9043.JPG|120px|Fahlsegler]]||[[Fahlsegler]]||''Apus pallidus''||Ausnahmeerscheinung|| ||
|- style="vertical-align:top"
|[[Datei:Pacific Swift.jpg|120px|Pazifiksegler]]||[[Pazifiksegler]]||''Apus pacificus''||besondere Ausnahmeerscheinung|| ||
|- style="vertical-align:top"
|[[Datei:House swift I2 IMG 3262 a.jpg|120px|Haussegler]]||[[Haussegler]]||''Apus affinis''||besondere Ausnahmeerscheinung|| ||
|}

== [[Otidiformes]] – Trappen ==
=== [[Otididae]] – Trappen ===
{| class="wikitable"
! width="12%"| Bild
! width="18%"| deutscher Name
! width="18%"| wissenschaftlicher Name
! width="22%"| Status
! width="8%"| RL-Status
! width="22%"| Bemerkung
|- style="vertical-align:top"
|[[Datei:Drop fúzatý (Otis tarda) (2416576086).jpg|120px|Großtrappe]]||[[Großtrappe]]||''Otis tarda''||seltener, lokaler Brut-, Jahresvogel||1||
|- style="vertical-align:top"
|[[Datei:Houbara Bustard in Talagang tehsil, Punjab, Pakistan.jpg|120px|Steppenkragentrappe]]||[[Steppenkragentrappe]]||''Chlamydotis macqueenii''||besondere Ausnahmeerscheinung||
|- style="vertical-align:top"
|[[Datei:Tetrax tetrax, Castuera, Estremadura, Spain 1.jpg|120px|Zwergtrappe]]||[[Zwergtrappe]]||''Tetrax tetrax''||Ausnahmeerscheinung||0||ehemaliger Brutvogel vor 1950
|}

== [[Cuculiformes]] – Kuckucksvögel ==
=== [[Cuculidae]] – Kuckucke ===
{| class="wikitable"
! width="12%"| Bild
! width="18%"| deutscher Name
! width="18%"| wissenschaftlicher Name
! width="22%"| Status
! width="8%"| RL-Status
! width="22%"| Bemerkung
|- style="vertical-align:top"
|[[Datei:Clamator glandarius (cropped).jpg|120px|Häherkuckuck]]||[[Häherkuckuck]]||''Clamator glandarius''||Ausnahmeerscheinung|| ||
|- style="vertical-align:top"
|[[Datei:Black-billed-cuckoo2.jpg|120px|Schwarzschnabelkuckuck]]||[[Schwarzschnabelkuckuck]]||''Coccyzus erythropthalmus''||besondere Ausnahmeerscheinung|| ||
|- style="vertical-align:top"
|[[Datei:Cuculus canorus vogelartinfo chris romeiks CHR0431 (cropped).jpg|120px|Kuckuck]]||[[Kuckuck]]||''Cuculus canorus''||Brut-, Zugvogel||3||
|}

== [[Pterocliformes]] – Flughühner ==
=== [[Pteroclidae]] – Flughühner ===
{| class="wikitable"
! width="12%"| Bild
! width="18%"| deutscher Name
! width="18%"| wissenschaftlicher Name
! width="22%"| Status
! width="8%"| RL-Status
! width="22%"| Bemerkung
|- style="vertical-align:top"
|[[Datei:Syrrhaptes paradoxus (Ján Svetlík) (cropped).jpg|120px|Steppenflughuhn]]||[[Steppenflughuhn]]||''Syrrhaptes paradoxus''||besondere Ausnahmeerscheinung|| ||ausnahmsweise Brutvogel vor 1950
|- style="vertical-align:top"
|[[Datei:Pterocles orientalis arenarius 208174952.jpg|120px|Sandflughuhn]]||[[Sandflughuhn]]||''Pterocles orientalis''|| || ||als Wildvogel nur vor 1950 nachgewiesen
|}

== [[Columbiformes]] – Taubenvögel ==
=== [[Columbidae]] – Tauben ===
{| class="wikitable"
! width="12%"| Bild
! width="18%"| deutscher Name
! width="18%"| wissenschaftlicher Name
! width="22%"| Status
! width="8%"| RL-Status
! width="22%"| Bemerkung
|- style="vertical-align:top"
|[[Datei:Feral pigeon Franconville 2022 01 21.jpg|120px|Straßentaube]]||[[Straßentaube]]||''Columba livia'' f. ''domestica''||eingeführter Brut-, Jahresvogel|| ||verwilderte Form der domestizierten [[Haustaube]]
|- style="vertical-align:top"
|[[Datei:ColumbaOenas.jpg|120px|Hohltaube]]||[[Hohltaube]]||''Columba oenas''||Brut-, Zugvogel|| ||
|- style="vertical-align:top"
|[[Datei:Columba palumbus 1 (Marek Szczepanek).jpg|120px|Ringeltaube]]||[[Ringeltaube]]||''Columba palumbus''||Brut-, Jahres-, Zugvogel, Wintergast|| ||
|- style="vertical-align:top"

In [23]:
queries = [i for i in data.split(sep="==")]

In [24]:
hits = list()
for query in queries:
    hits.append(re.findall(pattern=r"^^\|\[\[Datei:[^\]]*\]\]\|\|\[\[([^\[\]|]+)\]\]\|\|''([^']+)''\|\|([^|]*)\|\|([^|]*)", string = query, flags=re.MULTILINE))

In [25]:
import itertools
german_birds = list(itertools.chain.from_iterable(hits))

In [26]:
import pandas as pd

birds_df = pd.DataFrame(german_birds)

In [27]:
birds_df.columns = ["German_name", "Scientific_name", "Status", "Rl-status"]

In [28]:
birds_df.set_index("Scientific_name")

,German_name,Status,Rl-status
Scientific_name,,,
Tetrastes bonasia,Haselhuhn,"Brut-, Jahresvogel",2
Tetrao urogallus,Auerhuhn,"Brut-, Jahresvogel",1
Lyrurus tetrix,Birkhuhn,"Brut-, Jahresvogel",2
Lagopus muta,Alpenschneehuhn,"Brut-, Jahresvogel",R
Alectoris graeca,Steinhuhn,"seltener, lokaler Brut-, Jahresvogel",R
...,...,...,...
Emberiza bruniceps,Braunkopfammer,Ausnahmeerscheinung,
Emberiza spodocephala,Maskenammer,besondere Ausnahmeerscheinung,
Emberiza schoeniclus,Rohrammer,"Brut-, Zugvogel, Wintergast",
Setophaga americana,Meisenwaldsänger,besondere Ausnahmeerscheinung,
Setophaga virens,Grünmantel-Waldsänger,,

In [29]:
import pandas as pd

taxonomy = pd.read_csv("birds_taxonomy.csv")
taxonomy

,Unnamed: 0,Taxon_rank,Order,Family,Family_English_name,Scientific_name,English_name_AviList
0,0,order,Struthioniformes,NaN,NaN,Struthioniformes,NaN
1,1,family,Struthioniformes,Struthionidae,Ostriches,Struthionidae,NaN
2,2,genus,Struthioniformes,Struthionidae,Ostriches,Struthio,NaN
3,3,species,Struthioniformes,Struthionidae,Ostriches,Struthio molybdophanes,Somali Ostrich
4,4,species,Struthioniformes,Struthionidae,Ostriches,Struthio camelus,Common Ostrich
...,...,...,...,...,...,...,...
33679,33679,subspecies,Passeriformes,Thraupidae,Tanagers and Allies,Stilpnia cyanicollis cyanicollis,NaN
33680,33680,subspecies,Passeriformes,Thraupidae,Tanagers and Allies,Stilpnia cyanicollis cyanopygia,NaN
33681,33681,subspecies,Passeriformes,Thraupidae,Tanagers and Allies,Stilpnia cyanicollis hannahiae,NaN
33682,33682,subspecies,Passeriformes,Thraupidae,Tanagers and Allies,Stilpnia cyanicollis melanogaster,NaN
33683,33683,subspecies,Passeriformes,Thraupidae,Tanagers and Allies,Stilpnia cyanicollis albotibialis,NaN

In [30]:
birds_df.dtypes

German_name        str
Scientific_name    str
Status             str
Rl-status          str
dtype: object

In [31]:
taxonomy.dtypes

Unnamed: 0              int64
Taxon_rank                str
Order                     str
Family                    str
Family_English_name       str
Scientific_name           str
English_name_AviList      str
dtype: object

In [32]:
df_final = taxonomy.join(other=birds_df.set_index("Scientific_name"),
                          on="Scientific_name",
                          how="inner")

In [33]:
df_final = df_final.drop(columns='Unnamed: 0').copy()

In [35]:
df_final.reset_index(drop=True, inplace=True)
df_final

,Taxon_rank,Order,Family,Family_English_name,Scientific_name,English_name_AviList,German_name,Status,Rl-status
0,species,Anseriformes,Anatidae,"Ducks, Swans, and Geese",Oxyura leucocephala,White-headed Duck,Weißkopf-Ruderente,Ausnahmeerscheinung,
1,species,Anseriformes,Anatidae,"Ducks, Swans, and Geese",Oxyura jamaicensis,Ruddy Duck,Schwarzkopf-Ruderente,seltener Jahresvogel,
2,species,Anseriformes,Anatidae,"Ducks, Swans, and Geese",Cygnus olor,Mute Swan,Höckerschwan,"Brut-, Jahres-, Zugvogel, Wintergast",
3,species,Anseriformes,Anatidae,"Ducks, Swans, and Geese",Cygnus cygnus,Whooper Swan,Singschwan,"seltener Brutvogel; Zugvogel, Wintergast",
4,species,Anseriformes,Anatidae,"Ducks, Swans, and Geese",Branta bernicla,Brant Goose,Ringelgans,"Zugvogel, Wintergast",
...,...,...,...,...,...,...,...,...,...
452,species,Passeriformes,Emberizidae,Old World Buntings,Emberiza caesia,Cretzschmar's Bunting,Grauortolan,besondere Ausnahmeerscheinung,
453,species,Passeriformes,Emberizidae,Old World Buntings,Emberiza leucocephalos,Pine Bunting,Fichtenammer,Ausnahmeerscheinung,
454,species,Passeriformes,Emberizidae,Old World Buntings,Emberiza citrinella,Yellowhammer,Goldammer,"Brut-, Jahres-, Zugvogel, Wintergast",
455,species,Passeriformes,Parulidae,New World Warblers,Setophaga americana,Northern Parula,Meisenwaldsänger,besondere Ausnahmeerscheinung,
456,species,Passeriformes,Parulidae,New World Warblers,Setophaga virens,Black-throated Green Warbler,Grünmantel-Waldsänger,,

In [38]:
df_final.loc[160:180]

,Taxon_rank,Order,Family,Family_English_name,Scientific_name,English_name_AviList,German_name,Status,Rl-status
160,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Sterna hirundo,Common Tern,Flussseeschwalbe,"Brut-, Zugvogel",2
161,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Sterna dougallii,Roseate Tern,Rosenseeschwalbe,Ausnahmeerscheinung,0
162,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Hydrocoloeus minutus,Little Gull,Zwergmöwe,"seltener, lokaler Brutvogel; Zugvogel",R
163,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Rhodostethia rosea,Ross's Gull,Rosenmöwe,Ausnahmeerscheinung,
164,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Rissa tridactyla,Black-legged Kittiwake,Dreizehenmöwe,"lokaler Brut-, Jahres-, Zugvogel, Wintergast",2
165,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Xema sabini,Sabine's Gull,Schwalbenmöwe,seltener Zugvogel,
166,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Pagophila eburnea,Ivory Gull,Elfenbeinmöwe,Ausnahmeerscheinung,
167,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Chroicocephalus genei,Slender-billed Gull,Dünnschnabelmöwe,besondere Ausnahmeerscheinung,
168,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Chroicocephalus philadelphia,Bonaparte's Gull,Bonapartemöwe,besondere Ausnahmeerscheinung,\n
169,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Chroicocephalus ridibundus,Black-headed Gull,Lachmöwe,"Brut-, Jahres-, Zugvogel, Wintergast",
170,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Leucophaeus atricilla,Laughing Gull,Aztekenmöwe,Ausnahmeerscheinung,
171,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Leucophaeus pipixcan,Franklin's Gull,Präriemöwe,Ausnahmeerscheinung,
172,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Ichthyaetus ichthyaetus,Pallas's Gull,Fischmöwe,Ausnahmeerscheinung,
173,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Ichthyaetus audouinii,Audouin's Gull,Korallenmöwe,Ausnahmeerscheinung,
174,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Ichthyaetus melanocephalus,Mediterranean Gull,Schwarzkopfmöwe,"Brut-, Zugvogel, seltener Wintergast",
175,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Larus delawarensis,Ring-billed Gull,Ringschnabelmöwe,Ausnahmeerscheinung,
176,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Larus canus,Common Gull,Sturmmöwe,"Brut-, Jahres-, Zugvogel, Wintergast",
177,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Larus cachinnans,Caspian Gull,Steppenmöwe,"seltener Brutvogel; Zugvogel, Wintergast",
178,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Larus smithsonianus,American Herring Gull,Kanadamöwe,besondere Ausnahmeerscheinung,
179,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Larus marinus,Great Black-backed Gull,Mantelmöwe,"seltener Brutvogel; Jahres-, Zugvogel, Wintergast",
180,species,Charadriiformes,Laridae,"Skimmers, Noddies, Terns, and Gulls",Larus hyperboreus,Glaucous Gull,Eismöwe,seltener Wintergast,

In [36]:
df_final.to_csv("birds.csv")